title: Open Design 2018
description: A place for us to document our open design thoughts and processes.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
include: ["_pages"]
permalink: /:title/

sections: [
    ['week1', 'Week 1'],
    ['week2', 'Week 2'],
    ['week3', 'Week 3'],
    ['week4', 'Week 4'],
]


imageurl: "https://harryiliffe.github.io/open-design/assets/img/"
