title: Open Design 2018
description: A place for us to document our open design thoughts and processes.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
include: ["_pages"]
permalink: /:title/

sections: [
    ['research', 'Research'],
    ['ideation', 'Ideation'],
    ['presentations', 'Presentations'],
]


imageurl: "https://harryiliffe.github.io/open-design-2018/assets/img/"
